version: "3.8"

services:
  frontend:
    container_name: frontend-app-dev
    image: frontend-app-dev-image
    build:
      context: .
      target: development
    volumes:
      - ./client:/app
    ports:
      - 8000:8000
    environment:
      - WATCHPACK_POLLING=true
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
