version: "3.8"

services:
  api:
    container_name: rails-api-dev
    image: api-app-dev-image
    ports:
      - '3000:3000'
    build:
      context: ./api
    volumes:
      - ./api:/rails
    depends_on:
      - postgres
    links:
      - postgres
    environment:
        DB_HOST: local_pgdb
        DB_USER: rails
        DB_PASSWORD: rails
  frontend_react_vite:
    container_name: frontend-react-dev
    image: frontend-react-dev-image
    build:
      context: ./client
      target: development
      args:
        - NODE_ENV=development
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules/
    ports:
      - 8000:8000
    environment:
      WATCHPACK_POLLING: true
    depends_on:
      - postgres
  frontend_angular:
    container_name: frontend-angular-dev
    image: frontend-angular-dev-image
    build:
      context: ./client_angular
      target: development
      args:
        - NODE_ENV=development
    volumes:
      - ./client_angular:/app
      - /app/node_modules/
    ports:
      - 4200:4200
    expose:
      - 4200
    environment:
      WATCHPACK_POLLING: true
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: local_pgdb
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    expose:
      - 5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  local_pgdata:
  pgadmin-data:
